# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42fb24a604f52682d4c79ab1b632f873ee659097d6c91cc2042dc70fa974c4d5d40fa5123fd4b254dd4d3ad42af5a05f91bfbbe3cc88c412d88202ee1d3ac9a0

test:
  secret_key_base: 3b3cbe991e05bea9ac08eaab0c990b12f233b58acd61669459140c975097e83db48c01a73ee74dd99366848e5e4e10f144925ba2661106cec4fbcc7699d1dfe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
